const hash = "a".repeat(64);
const occurredAt = "2026-09-13T12:00:00.000Z";

export const caseRecord = {
  id: "case-1",
  version: 1,
  organizationId: "org-1",
  tenantId: "northstar",
  contactId: "contact-1",
  contactEmail: "maya@northstar.example",
  sourceThreadId: "thread-1",
  matchedEngineeringIssueId: "issue-1",
  workflow: "csv-export-v1",
  workflowVersion: 1,
  state: "WAITING_ENGINEERING",
  engineeringState: "CLOSED",
  latestVerificationId: "verification-1",
  notificationState: "NOT_DRAFTED",
  recoveryState: "NOT_OBSERVED",
  syncState: "NOT_REQUIRED",
  needsHumanReason: null,
  resumeState: null,
  createdAt: occurredAt,
  updatedAt: occurredAt,
} as const;

export const evidenceRecord = {
  id: "evidence-1",
  caseId: "case-1",
  provider: "github",
  sourceId: "issue-1",
  sourceUrl: "https://github.example/issues/1",
  retrievedAt: occurredAt,
  factKind: "REPORTED",
  fact: "The rollout was marked complete",
  redactedContent: "Rollout complete",
  contentHash: hash,
  environment: "LOCAL FIXTURE",
} as const;

export const verificationRecord = {
  id: "verification-1",
  caseId: "case-1",
  contractVersion: "csv-export-v1",
  input: {
    tenantId: "northstar",
    period: "2026-08",
    manifestRevision: 1,
    appRevision: 1,
    configRevision: 1,
    probeCredentialId: "probe-1",
  },
  requestId: "request-1",
  expected: {
    schema: ["record_id", "tenant_id", "period", "amount", "status"],
    rows: [
      {
        recordId: "record-1",
        tenantId: "northstar",
        period: "2026-08",
        amount: "42.00",
        status: "settled",
      },
    ],
  },
  observed: {
    httpStatus: 200,
    schema: ["record_id", "tenant_id", "period", "amount", "status"],
    rows: [],
    failureReason: "Expected one record but observed zero",
  },
  responseHash: hash,
  normalizedContentHash: hash,
  result: "FAIL",
  verifiedAt: occurredAt,
} as const;

export const actionRecord = {
  id: "action-1",
  caseId: "case-1",
  version: 1,
  logicalKey: "case-1:github:impact",
  provider: "github",
  kind: "create-impact-issue",
  payload: { title: "Northstar export remains empty" },
  payloadHash: hash,
  status: "PLANNED",
  attempts: [],
  providerIds: [],
  uncertaintyReason: null,
  error: null,
  createdAt: occurredAt,
  updatedAt: occurredAt,
} as const;

export const approvalRecord = {
  id: "approval-1",
  caseId: "case-1",
  organizationId: "org-1",
  tenantId: "northstar",
  caseVersion: 1,
  actionId: "action-1",
  actionVersion: 1,
  actionHash: hash,
  providerAccountId: "gmail-1",
  draftId: "draft-1",
  threadId: "thread-1",
  sender: "support@reportdesk.example",
  recipients: ["maya@northstar.example"],
  subject: "Your CSV export",
  body: "Please retry your export.",
  approvedMime: "bWltZQ==",
  businessFieldsHash: hash,
  verificationId: "verification-1",
  appRevision: 1,
  configRevision: 1,
  policyVersion: "policy-1",
  approverId: null,
  slackWorkspaceId: "workspace-1",
  slackChannelId: "channel-1",
  slackMessageId: "message-1",
  nonce: "nonce-1",
  decision: "PENDING",
  expiresAt: "2026-09-13T12:05:00.000Z",
  consumedAt: null,
  revokedAt: null,
  createdAt: occurredAt,
} as const;

export const outcomeEventRecord = {
  eventId: "event-1",
  caseId: "case-1",
  tenantId: "northstar",
  actorType: "CUSTOMER",
  actorId: "maya",
  workflow: "csv-export-v1",
  manifestRevision: 1,
  appRevision: 1,
  configRevision: 1,
  requestId: "request-2",
  result: "SUCCEEDED",
  occurredAt,
  signature: "signature",
} as const;

export const runRecord = {
  id: "run-1",
  caseId: "case-1",
  commit: "abcdef0",
  promptRevision: "prompt-1",
  modelId: "model-1",
  configId: "config-1",
  releaseId: "release-1",
  environments: {
    gmail: "NOT RUN",
    github: "LOCAL FIXTURE",
    slack: "NOT RUN",
    reportdesk: "LOCAL FIXTURE",
  },
  status: "RUNNING",
  startedAt: occurredAt,
  finishedAt: null,
  durationMs: null,
  inputTokens: null,
  outputTokens: null,
  toolCallCount: 0,
  stopReason: null,
  traceId: null,
} as const;
